version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_NAME=speed_monitor
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=speed_monitor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    restart: unless-stopped

  collector:
    build:
      context: ./collector
      target: development
    volumes:
      - ./collector:/app
    environment:
      - DB_HOST=db
      - DB_NAME=speed_monitor
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
